import * as vscode from "vscode";
import * as path from "path";
import * as fs from "fs";
import { BaseState } from "../types";
import { getFastIOContent } from "../generators/fastioContent";
import { getJavaTemplate } from "../generators/javaTemplate";
import { generateMarkdown } from "../generators/markdown";
import { getGenContent } from "../generators/genContent";
import FileManager from "../helper/FileManager";

export default async function pull(state: BaseState) {
  if (!state.browserContext) {
    vscode.window.showErrorMessage("Browser not launched!");
    return;
  }

  const pages = state.browserContext.pages();
  const page = pages[pages.length - 1];

  const data = await page.evaluate(() => {
    const getElText = (sel: string) =>
      document.querySelector(sel)?.textContent?.trim() || "";

    // Delete extra spans generated by MathJax
    document
      .querySelectorAll("span.MathJax, span.MathJax_Preview")
      .forEach((el) => el.remove());

    // Add $..$ sign to the existing valid latex formulas so that vscode can render them in md
    document.querySelectorAll('script[type="math/tex"]').forEach((el, i) => {
      el.replaceWith(`$${el.textContent}$`);
    });

    // 1. Get Title and Label (e.g., "F. Coprime Graph")
    const fullTitle = getElText(".header .title");
    const label = fullTitle.split(".")[0] || "A";

    // 2. Comprehensive Description Extraction
    // Codeforces descriptions are often multiple divs before the input specification
    const statement = document.querySelector(".header + div");
    const descriptionDivs = statement
      ? Array.from(statement.children)
          .map((child) => child.textContent?.trim())
          .join("\n\n")
      : "";

    const inputSpec = getElText(".input-specification");
    const outputSpec = getElText(".output-specification");
    const note = getElText(".note");

    const timeLimit = getElText(".time-limit")
      .replace("time limit per test", "")
      .trim();
    const memoryLimit = getElText(".memory-limit")
      .replace("memory limit per test", "")
      .trim();

    const inputs = Array.from(document.querySelectorAll(".input pre")).map(
      (el) =>
        Array.from(el.childNodes)
          .map((d) => d.textContent)
          .join("\n"),
    );
    const outputs = Array.from(document.querySelectorAll(".output pre")).map(
      (el) =>
        Array.from(el.childNodes)
          .map((d) => d.textContent)
          .join("\n"),
    );

    return {
      title: fullTitle,
      label,
      timeLimit,
      memoryLimit,
      description: descriptionDivs,
      inputSpec: inputSpec.slice(5, inputSpec.length),
      outputSpec: outputSpec.slice(6, outputSpec.length),
      note,
      inputs,
      outputs,
    };
  });

  // --- FILE SYSTEM LOGIC ---
  const problemFolderName = data.title.replace(/[:*?"<>|]/g, ""); // Sanitize
  const fileManager = new FileManager();
  // Create Dir in root
  fileManager.changeDirOrCreate(problemFolderName);

  // Generate Files
  fileManager.writeFiles([
    {
      fileName: "Instructions.md",
      content: generateMarkdown(data),
    },
    {
      fileName: `${data.label}.java`,
      content: getJavaTemplate(data.label),
    },
    { fileName: "FastIO.java", content: getFastIOContent() },
  ]);

  // Create tests in root/problem-name
  fileManager.changeDirOrCreate(path.join(problemFolderName, "tests"));

  let testcaseId = 1;
  for (let i = 0; i < data.inputs.length; i++) {
    const input = data.inputs[i];
    const output = data.outputs[i];
    fileManager.write(`input${testcaseId}.txt`, input || "");
    fileManager.write(`expected${testcaseId}.txt`, output || "");
    testcaseId++;
  }
  fileManager.goBack();

  fileManager.write(`Gen.java`, getGenContent(testcaseId));

  // Open the Java file
  await fileManager.openInVscode(`${data.label}.java`);

  vscode.window.showInformationMessage(`Pulled ${data.title} successfully!`);
}
